language: generic

dist: trusty

services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE="latex"
    - env: DOCKER_IMAGE="serverless-go"
    - env: DOCKER_IMAGE="kube-manage"
    - env: DOCKER_IMAGE="sonarqube"

# don't rebuild image : git diff HEAD~1 -- latex | wc -l
script:
  - if [[ "${TRAVIS_BRANCH}" != 'master' ]] || [[ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]] ; then make test folder=$DOCKER_IMAGE; fi
  - if [[ "${TRAVIS_BRANCH}" == 'master' ]] && [[ "${TRAVIS_EVENT_TYPE}" != "pull_request"  ]] ; then make deploy-ci folder=$DOCKER_IMAGE; fi