language: generic

dist: trusty

services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE="latex"
    - env: DOCKER_IMAGE="serverless-go"

script:
  - chmod +x *.sh
  - ./build.sh $DOCKER_IMAGE
  - ./deploy.sh $DOCKER_IMAGE