language: generic

dist: trusty

services:
  - docker

matrix:
  include:
    - env: DOCKER_IMAGE="latex"
    - env: DOCKER_IMAGE="serverless-go"
    - env: DOCKER_IMAGE="kube-manage"

script:
  - if [[ "${TRAVIS_BRANCH}" != 'master' ]] ; then make test img=$DOCKER_IMAGE; fi
  - if [[ "${TRAVIS_BRANCH}" == 'master' ]] ; then make deploy-ci img=$DOCKER_IMAGE; fi